"""fixed models

Revision ID: 5e0d282f95e4
Revises: 8c9fbc90e63b
Create Date: 2025-07-03 22:14:55.481441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e0d282f95e4'
down_revision = '8c9fbc90e63b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
