"""charity

Revision ID: 80250ca48727
Revises: 984580cb573c
Create Date: 2025-07-03 20:34:38.183066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80250ca48727'
down_revision = '984580cb573c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
