"""fixed models

Revision ID: 8c9fbc90e63b
Revises: d04ca084847b
Create Date: 2025-07-03 21:18:37.446940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c9fbc90e63b'
down_revision = 'd04ca084847b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
